site_name: pixel-engine
docs_dir: docs
site_dir: build/mkdocs-site
validation:
  nav:
    omitted_files: ignore
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore
nav:
  - 设计文档: 设计文档.md
