from __future__ import annotations

import hashlib
import tempfile
import unittest
from pathlib import Path

from tools import generate_unicode_bidi_data as generator


class UnicodeBidiGeneratorTest(unittest.TestCase):
    """Verifies pinned-input parsing and fail-closed generated-artifact checks."""

    def test_local_input_requires_exact_digest(self) -> None:
        """A local mirror is accepted only when its bytes match the reviewed SHA-256."""

        # Deterministic local payload used as a miniature official input.
        payload = b"reviewed Unicode bytes\n"
        # Matching specification whose nested path exercises local mirror resolution.
        specification = generator.OfficialInput(
            filename="extracted/sample.txt",
            url="https://example.invalid/sample.txt",
            sha256=hashlib.sha256(payload).hexdigest(),
        )
        with tempfile.TemporaryDirectory() as temporary_directory:
            # Temporary offline mirror root isolated from repository outputs.
            mirror = Path(temporary_directory)
            # Nested file path matching the upstream relative name.
            source = mirror / specification.filename
            source.parent.mkdir(parents=True)
            source.write_bytes(payload)

            self.assertEqual(payload, generator.load_official_input(specification, mirror))
            source.write_bytes(payload + b"drift")
            with self.assertRaisesRegex(ValueError, "SHA-256 mismatch"):
                generator.load_official_input(specification, mirror)

    def test_bidi_class_missing_ranges_and_explicit_rows_have_fixed_precedence(self) -> None:
        """Specialized @missing ranges apply before explicit property rows override them."""

        # Minimal UCD excerpt retaining the source-order precedence used by Unicode 17.
        payload = b"\n".join(
            (
                b"# @missing: 0000..10FFFF; Left_To_Right",
                b"# @missing: 0590..05FF; Right_To_Left",
                b"05D0 ; AL # explicit override",
            )
        )

        # Complete code-point vector produced by the production parser.
        values = generator.parse_bidi_classes(payload)

        self.assertEqual("L", values[0x0041])
        self.assertEqual("R", values[0x0590])
        self.assertEqual("AL", values[0x05D0])
        self.assertEqual("L", values[0x0600])

    def test_bracket_pair_identity_follows_canonical_singletons(self) -> None:
        """BD16 gives canonical-equivalent angle brackets the same generated pair identity."""

        # Paired-bracket rows containing both canonical and equivalent scalar pairs.
        brackets = b"\n".join(
            (
                b"2329; 232A; o",
                b"232A; 2329; c",
                b"3008; 3009; o",
                b"3009; 3008; c",
            )
        )

        # Parsed entries indexed by their bracket scalar for direct identity assertions.
        entries = {entry[0]: entry for entry in generator.parse_brackets(brackets)}

        self.assertEqual(
            "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
            generator.UNICODE_DATA_SHA256,
        )
        self.assertEqual(0x3008, entries[0x2329][3])
        self.assertEqual(entries[0x2329][3], entries[0x3008][3])
        self.assertEqual(entries[0x232A][3], entries[0x3009][3])

    def test_write_or_check_rejects_missing_and_stale_outputs(self) -> None:
        """Check mode never writes and reports both missing and byte-different artifacts."""

        # Exact generated bytes used for the isolated artifact lifecycle.
        expected = b"generated\n"
        with tempfile.TemporaryDirectory() as temporary_directory:
            # Destination representing one checked-in generated artifact.
            destination = Path(temporary_directory) / "generated.kt"
            with self.assertRaisesRegex(FileNotFoundError, "missing"):
                generator.write_or_check(destination, expected, check=True)

            generator.write_or_check(destination, expected, check=False)
            generator.write_or_check(destination, expected, check=True)
            destination.write_bytes(b"stale\n")
            with self.assertRaisesRegex(ValueError, "stale"):
                generator.write_or_check(destination, expected, check=True)
            self.assertEqual(b"stale\n", destination.read_bytes())


if __name__ == "__main__":
    unittest.main()
