// 由 tools/generate_pixel_font_catalog.py 生成；禁止手工修改。
package com.purride.pixellauncherv2.launcher

/** 由 fonts/font_catalog.json 生成的只读字体目录。 */
internal object GeneratedPixelFontCatalog {
    /** 按设置页展示顺序排列的全部字体家族。 */
    val families: List<FontFamilyDescriptor> = listOf(
        FontFamilyDescriptor(
            id = LauncherFontFamily("fusion"),
            constantName = "FUSION",
            displayLabel = "FUSION",
            assetFamilyId = "fusion_pixel",
            sourceVersion = "bundled",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("fusion"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(10),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("fusion"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(8),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(8),
                        cellHeight = 8,
                        baseline = 7,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 8,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "fusion_pixel_8px_proportional_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_proportional_latin",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-8px-proportional-latin.ttf",
                            sourceSha256 = "67cbf707280e04b79f928718a781772a8551f3a39c349eb1f0f57ecdeb14c277",
                            rangeSet = "standard",
                            defaultAdvance = 4,
                        ),
                        FontPackDescriptor(
                            id = "fusion_pixel_8px_proportional_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_proportional_zh_hans",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-8px-proportional-zh_hans.ttf",
                            sourceSha256 = "d6d9cfa965e7d7a29556c22a6a5166ced84e13130096fb99f2fe86d2881342dd",
                            rangeSet = "standard",
                            defaultAdvance = 8,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("fusion"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 9,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "fusion_pixel_10px_proportional_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_proportional_latin",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-10px-proportional-latin.ttf",
                            sourceSha256 = "57c096e56044dba49ab3eeb1c4127dcfc2391b36c7982d1fb010d7144c56a18d",
                            rangeSet = "standard",
                            defaultAdvance = 6,
                        ),
                        FontPackDescriptor(
                            id = "fusion_pixel_10px_proportional_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_proportional_zh_hans",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-10px-proportional-zh_hans.ttf",
                            sourceSha256 = "0aabedf0139a9d5532dbbe73e0cff4889a47fb92b05b03e2a0f1e2db55537265",
                            rangeSet = "standard",
                            defaultAdvance = 10,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("fusion"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(12),
                        cellHeight = 12,
                        baseline = 11,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "fusion_pixel_12px_proportional_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_proportional_latin",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-12px-proportional-latin.ttf",
                            sourceSha256 = "5d6490677cc68e2fb7c6efe76552a9884981d7dc4a480c02385ebcce3a662a4c",
                            rangeSet = "standard",
                            defaultAdvance = 8,
                        ),
                        FontPackDescriptor(
                            id = "fusion_pixel_12px_proportional_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_proportional_zh_hans",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-12px-proportional-zh_hans.ttf",
                            sourceSha256 = "2e36bb4b1ee5399394b50b59b91c5864a46b615ec2b28b9d2b6a7ca4de091fa7",
                            rangeSet = "standard",
                            defaultAdvance = 12,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("fusion"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(8),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(8),
                        cellHeight = 8,
                        baseline = 7,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 8,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "fusion_pixel_8px_monospaced_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_monospaced_latin",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-8px-monospaced-latin.ttf",
                            sourceSha256 = "82bda18bde6f82eb112d3544aef59139fe3f376f38a6fe279e02579ef2c1bab1",
                            rangeSet = "standard",
                            defaultAdvance = 8,
                        ),
                        FontPackDescriptor(
                            id = "fusion_pixel_8px_monospaced_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_monospaced_zh_hans",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-8px-monospaced-zh_hans.ttf",
                            sourceSha256 = "e71e80e58b2555e8cd419cae31c51aa0ec563d4af38cf93ba25c1aec19ca26fc",
                            rangeSet = "standard",
                            defaultAdvance = 8,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("fusion"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 9,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "fusion_pixel_10px_monospaced_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_monospaced_latin",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-10px-monospaced-latin.ttf",
                            sourceSha256 = "b0d279285883fad030509c8ae9abff22d312ae0fe872b88622e24754dcc30368",
                            rangeSet = "standard",
                            defaultAdvance = 10,
                        ),
                        FontPackDescriptor(
                            id = "fusion_pixel_10px_monospaced_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_monospaced_zh_hans",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-10px-monospaced-zh_hans.ttf",
                            sourceSha256 = "825178fc7f5dcbdaabcd4787076b5a77e59685bef6516b04db22cc014b4c3f22",
                            rangeSet = "standard",
                            defaultAdvance = 10,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("fusion"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(12),
                        cellHeight = 12,
                        baseline = 10,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "fusion_pixel_12px_monospaced_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_monospaced_latin",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-12px-monospaced-latin.ttf",
                            sourceSha256 = "53b7ece5e922df0b1e647be390ee2601fc74bc8da4922ddb22344c5529319a49",
                            rangeSet = "standard",
                            defaultAdvance = 12,
                        ),
                        FontPackDescriptor(
                            id = "fusion_pixel_12px_monospaced_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_monospaced_zh_hans",
                            sourceType = "ttf",
                            sourcePath = "app/src/main/assets/fonts/fusion-pixel-12px-monospaced-zh_hans.ttf",
                            sourceSha256 = "0582247a2d5e5240ac8ccb2e18de2253eab59a0764ac807420eb2fdfb6910b42",
                            rangeSet = "standard",
                            defaultAdvance = 12,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("ark"),
            constantName = "ARK",
            displayLabel = "ARK",
            assetFamilyId = "ark_pixel",
            sourceVersion = "2026.07.20",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("ark"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(10),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("ark"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 8,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "ark_pixel_10px_proportional_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_10px_proportional_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-10px-proportional-zh_cn.bdf",
                            sourceSha256 = "4cdb03df957b45439658944ea8eda169113cb4276e8ac52ec236dab794501c31",
                            rangeSet = "bmp",
                            defaultAdvance = 5,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("ark"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(12),
                        cellHeight = 12,
                        baseline = 10,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "ark_pixel_12px_proportional_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_12px_proportional_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-12px-proportional-zh_cn.bdf",
                            sourceSha256 = "e83acfb188b82c5ae0384b59afaf92d38795c30235afa69e2f8d6ad08f13ce6c",
                            rangeSet = "bmp",
                            defaultAdvance = 6,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("ark"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(16),
                        cellHeight = 16,
                        baseline = 13,
                        narrowAdvanceWidth = 7,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "ark_pixel_16px_proportional_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_16px_proportional_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-16px-proportional-zh_cn.bdf",
                            sourceSha256 = "694fa5400941e6281b025e59e3cdddea0a306fca246e8e12e0d004fbcab8c109",
                            rangeSet = "bmp",
                            defaultAdvance = 7,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("ark"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 9,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "ark_pixel_10px_monospaced_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_10px_monospaced_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-10px-monospaced-zh_cn.bdf",
                            sourceSha256 = "7e2d5351b5121e2c1343cada1a076cd4f7724aef2f4617a1c3a8b10c5af8d236",
                            rangeSet = "bmp",
                            defaultAdvance = 5,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("ark"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(12),
                        cellHeight = 12,
                        baseline = 10,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "ark_pixel_12px_monospaced_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_12px_monospaced_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-12px-monospaced-zh_cn.bdf",
                            sourceSha256 = "bf1ba88061952a88ae15b8fb67f55a69589f73bd77296fe31eafaaed36d38e39",
                            rangeSet = "bmp",
                            defaultAdvance = 6,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("ark"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(16),
                        cellHeight = 16,
                        baseline = 13,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "ark_pixel_16px_monospaced_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_16px_monospaced_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-16px-monospaced-zh_cn.bdf",
                            sourceSha256 = "24784e5587ecd288e2770aab0656b1b355e8e5ade572e3937662d20524227aec",
                            rangeSet = "bmp",
                            defaultAdvance = 8,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("cubic_11"),
            constantName = "CUBIC_11",
            displayLabel = "CUBIC 11",
            assetFamilyId = "cubic_11",
            sourceVersion = "1.500",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("cubic_11"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(11),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("cubic_11"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 8,
                        narrowAdvanceWidth = 7,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "cubic_11_10px_proportional",
                            assetDirectory = "glyphpacks/cubic_11_10px_proportional",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/cubic_11/1.500/Cubic_11.ttf",
                            sourceSha256 = "0193f5f033612496df6b45ee92ac3b335bc6a5a24ff95da55ca87b33e57dcf62",
                            rangeSet = "bmp",
                            defaultAdvance = 7,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("cubic_11"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(11),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(11),
                        cellHeight = 14,
                        baseline = 10,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "cubic_11_11px_proportional",
                            assetDirectory = "glyphpacks/cubic_11_11px_proportional",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/cubic_11/1.500/Cubic_11.ttf",
                            sourceSha256 = "0193f5f033612496df6b45ee92ac3b335bc6a5a24ff95da55ca87b33e57dcf62",
                            rangeSet = "bmp",
                            defaultAdvance = 8,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("boutique_7"),
            constantName = "BOUTIQUE_7",
            displayLabel = "BOUTIQUE 7",
            assetFamilyId = "boutique_7",
            sourceVersion = "2026.03.30",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("boutique_7"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(7),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("boutique_7"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(7),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(7),
                        cellHeight = 8,
                        baseline = 6,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 7,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "boutique_7_7px_proportional",
                            assetDirectory = "glyphpacks/boutique_7_7px_proportional",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/boutique_bitmap_7/current-2026.03.30/BoutiqueBitmap7x7.ttf",
                            sourceSha256 = "25b76e6e0545ca46f3be26b8fc179e0a6af40367ded75aeada3b56a61fa3cda1",
                            rangeSet = "bmp",
                            defaultAdvance = 4,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("boutique_7"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 8,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "boutique_7_10px_proportional",
                            assetDirectory = "glyphpacks/boutique_7_10px_proportional",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/boutique_bitmap_7/current-2026.03.30/BoutiqueBitmap7x7.ttf",
                            sourceSha256 = "25b76e6e0545ca46f3be26b8fc179e0a6af40367ded75aeada3b56a61fa3cda1",
                            rangeSet = "bmp",
                            defaultAdvance = 6,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("boutique_9"),
            constantName = "BOUTIQUE_9",
            displayLabel = "BOUTIQUE 9",
            assetFamilyId = "boutique_9",
            sourceVersion = "1.93",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("boutique_9"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(9),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("boutique_9"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(9),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(9),
                        cellHeight = 11,
                        baseline = 8,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 9,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "boutique_9_9px_proportional",
                            assetDirectory = "glyphpacks/boutique_9_9px_proportional",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/boutique_bitmap_9/1.93/BoutiqueBitmap9x9_1.93.ttf",
                            sourceSha256 = "7210391e4252471fbd9b62f65d86f1f7bcdc7f8beb4fc1feeb3ad8b65a0e85e8",
                            rangeSet = "bmp",
                            defaultAdvance = 6,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("boutique_9"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 7,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "boutique_9_10px_proportional",
                            assetDirectory = "glyphpacks/boutique_9_10px_proportional",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/boutique_bitmap_9/1.93/BoutiqueBitmap9x9_1.93.ttf",
                            sourceSha256 = "7210391e4252471fbd9b62f65d86f1f7bcdc7f8beb4fc1feeb3ad8b65a0e85e8",
                            rangeSet = "bmp",
                            defaultAdvance = 6,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("dotted_circle"),
            constantName = "DOTTED_CIRCLE",
            displayLabel = "DOTTED O",
            assetFamilyId = "dotted_circle",
            sourceVersion = "0.1",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("dotted_circle"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(16),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("dotted_circle"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 7,
                        narrowAdvanceWidth = 7,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "dotted_circle_10px_proportional",
                            assetDirectory = "glyphpacks/dotted_circle_10px_proportional",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiCircleRegular.otf",
                            sourceSha256 = "7b2c41e821d7091bed42df0158c130d62aeabdda7fde31b2754b1b7017cfb2d1",
                            rangeSet = "bmp",
                            defaultAdvance = 7,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("dotted_circle"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(16),
                        cellHeight = 18,
                        baseline = 13,
                        narrowAdvanceWidth = 11,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "dotted_circle_16px_proportional",
                            assetDirectory = "glyphpacks/dotted_circle_16px_proportional",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiCircleRegular.otf",
                            sourceSha256 = "7b2c41e821d7091bed42df0158c130d62aeabdda7fde31b2754b1b7017cfb2d1",
                            rangeSet = "bmp",
                            defaultAdvance = 11,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("dotted_square"),
            constantName = "DOTTED_SQUARE",
            displayLabel = "DOTTED []",
            assetFamilyId = "dotted_square",
            sourceVersion = "0.1",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("dotted_square"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(16),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("dotted_square"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 7,
                        narrowAdvanceWidth = 7,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "dotted_square_10px_proportional",
                            assetDirectory = "glyphpacks/dotted_square_10px_proportional",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiSquareRegular.otf",
                            sourceSha256 = "c5823b88b35937b638b85cf8ba35d4b9a94b4d3b58c981550ddca7cb39c86714",
                            rangeSet = "bmp",
                            defaultAdvance = 7,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("dotted_square"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(16),
                        cellHeight = 18,
                        baseline = 13,
                        narrowAdvanceWidth = 11,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "dotted_square_16px_proportional",
                            assetDirectory = "glyphpacks/dotted_square_16px_proportional",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiSquareRegular.otf",
                            sourceSha256 = "c5823b88b35937b638b85cf8ba35d4b9a94b4d3b58c981550ddca7cb39c86714",
                            rangeSet = "bmp",
                            defaultAdvance = 11,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("dotted_diamond"),
            constantName = "DOTTED_DIAMOND",
            displayLabel = "DOTTED <>",
            assetFamilyId = "dotted_diamond",
            sourceVersion = "0.1",
            licenseId = "OFL-1.1",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("dotted_diamond"),
                widthMode = LauncherFontWidthMode.PROPORTIONAL,
                size = PixelFontSize(16),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("dotted_diamond"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 7,
                        narrowAdvanceWidth = 7,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "dotted_diamond_10px_proportional",
                            assetDirectory = "glyphpacks/dotted_diamond_10px_proportional",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiDiamondRegular.otf",
                            sourceSha256 = "9a82a5d521ea0e3d131570750d3ecaa9ab226c94615c15163cddb08e6dd9f7d0",
                            rangeSet = "bmp",
                            defaultAdvance = 7,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("dotted_diamond"),
                        widthMode = LauncherFontWidthMode.PROPORTIONAL,
                        size = PixelFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(16),
                        cellHeight = 18,
                        baseline = 13,
                        narrowAdvanceWidth = 11,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "dotted_diamond_16px_proportional",
                            assetDirectory = "glyphpacks/dotted_diamond_16px_proportional",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiDiamondRegular.otf",
                            sourceSha256 = "9a82a5d521ea0e3d131570750d3ecaa9ab226c94615c15163cddb08e6dd9f7d0",
                            rangeSet = "bmp",
                            defaultAdvance = 11,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("gnu_unifont"),
            constantName = "GNU_UNIFONT",
            displayLabel = "UNIFONT",
            assetFamilyId = "gnu_unifont",
            sourceVersion = "17.0.04",
            licenseId = "GPL-2.0+",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("gnu_unifont"),
                widthMode = LauncherFontWidthMode.MONOSPACED,
                size = PixelFontSize(16),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("gnu_unifont"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 8,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "gnu_unifont_10px_monospaced",
                            assetDirectory = "glyphpacks/gnu_unifont_10px_monospaced",
                            sourceType = "otf",
                            sourcePath = "tools/font_sources/gnu_unifont/17.0.04/unifont-17.0.04.otf",
                            sourceSha256 = "d1f664a9753b9c6b7ff357128749e32b5d3eee90c7c03618363fabd43a39b5b7",
                            rangeSet = "bmp",
                            defaultAdvance = 5,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("gnu_unifont"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(16),
                        cellHeight = 16,
                        baseline = 14,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "gnu_unifont_16px_monospaced",
                            assetDirectory = "glyphpacks/gnu_unifont_16px_monospaced",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/gnu_unifont/17.0.04/unifont-17.0.04.bdf.gz",
                            sourceSha256 = "9a2de4826388242771121c7fe00e412523c318318b8ee38e6be6cd454e7ec802",
                            rangeSet = "bmp",
                            defaultAdvance = 8,
                        ),
                    ),
                ),
            ),
        ),
        FontFamilyDescriptor(
            id = LauncherFontFamily("pix32"),
            constantName = "PIX32",
            displayLabel = "PIX32",
            assetFamilyId = "pix32",
            sourceVersion = "1.9.7",
            licenseId = "commercial-purchased-user-declared",
            defaultKey = FontFaceKey(
                family = LauncherFontFamily("pix32"),
                widthMode = LauncherFontWidthMode.MONOSPACED,
                size = PixelFontSize(12),
            ),
            faces = listOf(
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("pix32"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(10),
                    ),
                    settingsVisible = false,
                    roles = setOf(LauncherTextRole.CHROME_10),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(10),
                        cellHeight = 10,
                        baseline = 8,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "pix32_10px_monospaced",
                            assetDirectory = "glyphpacks/pix32_10px_monospaced",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/pix32/1.9.7/Pixel32.v1.9.7.ttf",
                            sourceSha256 = "06a8a1714f77ca598177e2ac1d3b4af14f4c04c1acf101f1fcbc2af2a136c451",
                            rangeSet = "bmp",
                            defaultAdvance = 5,
                        ),
                    ),
                ),
                FontFaceDescriptor(
                    key = FontFaceKey(
                        family = LauncherFontFamily("pix32"),
                        widthMode = LauncherFontWidthMode.MONOSPACED,
                        size = PixelFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = PixelFontMetrics(
                        size = PixelFontSize(12),
                        cellHeight = 14,
                        baseline = 11,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        FontPackDescriptor(
                            id = "pix32_12px_monospaced",
                            assetDirectory = "glyphpacks/pix32_12px_monospaced",
                            sourceType = "ttf",
                            sourcePath = "tools/font_sources/pix32/1.9.7/Pixel32.v1.9.7.ttf",
                            sourceSha256 = "06a8a1714f77ca598177e2ac1d3b4af14f4c04c1acf101f1fcbc2af2a136c451",
                            rangeSet = "bmp",
                            defaultAdvance = 6,
                        ),
                    ),
                ),
            ),
        ),
    )
}
