package com.purride.pixellauncherv2.launcher

import com.purride.pixellauncherv2.render.PixelShape
import com.purride.pixellauncherv2.render.ScreenProfileFactory
import com.purride.pixellauncherv2.data.SmsMessageEntry
import com.purride.pixellauncherv2.data.SmsThreadSummary
import com.purride.pixellauncherv2.data.UnreadSmsEntry

data class LauncherState(
    val apps: List<AppEntry> = emptyList(),
    val drawerVisibleApps: List<AppEntry> = emptyList(),
    val drawerQuery: String = "",
    val isDrawerSearchFocused: Boolean = false,
    val isDrawerRailSliding: Boolean = false,
    val isAppActionMenuVisible: Boolean = false,
    val selectedIndex: Int = 0,
    val listStartIndex: Int = 0,
    val drawerPageIndex: Int = 0,
    val drawerFocus: DrawerFocus = DrawerFocus.LIST,
    val isLoading: Boolean = true,
    val currentTimeText: String = "",
    val currentDateText: String = "",
    val currentWeekdayText: String = "",
    val mode: LauncherMode = LauncherMode.HOME,
    val returnMode: LauncherMode = LauncherMode.HOME,
    val settingsSelectedIndex: Int = 0,
    val settingsListStartIndex: Int = 0,
    val appEditorSelectedIndex: Int = 0,
    val appEditorNameDraft: String = "",
    val appEditorAliasDraft: String = "",
    val unreadSmsEntries: List<UnreadSmsEntry> = emptyList(),
    val smsSelectedIndex: Int = 0,
    val smsListStartIndex: Int = 0,
    val smsThreads: List<SmsThreadSummary> = emptyList(),
    val isSmsThreadsLoading: Boolean = false,
    val smsThreadSelectedIndex: Int = 0,
    val smsThreadListStartIndex: Int = 0,
    val smsCurrentThreadId: Long? = null,
    val smsCurrentAddress: String = "",
    val smsMessages: List<SmsMessageEntry> = emptyList(),
    val smsThreadSearchQuery: String = "",
    val smsDraftText: String = "",
    val smsSendStatusText: String = "",
    val isDefaultSmsApp: Boolean = false,
    val smsPermissionState: SmsPermissionState = SmsPermissionState.MISSING,
    val selectedPixelShape: PixelShape = PixelShape.SQUARE,
    val selectedDotSizePx: Int = ScreenProfileFactory.defaultDotSizePx,
    val isPixelGapEnabled: Boolean = true,
    val selectedTheme: PixelTheme = PixelTheme.DAY,
    val drawerListAlignment: DrawerListAlignment = DrawerListAlignment.LEFT,
    val isIdlePageEnabled: Boolean = false,
    val chargeAutoIdleEnabled: Boolean = false,
    val inactivityAutoIdleEnabled: Boolean = true,
    val idleTimeoutSeconds: Int = IdleSettings.DEFAULT_TIMEOUT_SECONDS,
    val openDrawerInSearchMode: Boolean = false,
    val chargeIdleEffect: ChargeIdleEffect = ChargeIdleEffect.FLUID,
    val batteryLevel: Int = 100,
    val isCharging: Boolean = false,
    val recentApps: List<String> = emptyList(),
    val lastInteractionUptimeMs: Long = 0L,
    val launchCount: Int = 0,
    val lastLaunchPackageName: String? = null,
    val terminalStatusText: String = "",
    val nextAlarmText: String = "--:--",
    val missedCallCount: Int = 0,
    val unreadSmsCount: Int = 0,
    val notificationSummaryText: String = "",
    val notificationCount: Int = 0,
    val notificationSources: List<NotificationSourceInfo> = emptyList(),
    val mutedNotificationSourceIds: Set<String> = emptySet(),
    val priorityNotificationSourceIds: Set<String> = emptySet(),
    val rainHintText: String = "",
    val rainUpdatedTimeText: String = "",
    val screenUsageTimeText: String = "--:--",
    val screenOpenCountText: String = "--",
    val statusBarMessageText: String = "",
    val hasUsageAccess: Boolean = false,
    val hasLocationPermission: Boolean = false,
    val hasCallLogPermission: Boolean = false,
    val hasSmsReadPermission: Boolean = false,
    val hasPostNotificationPermission: Boolean = false,
    val hasNotificationListenerAccess: Boolean = false,
    val dataHealthUpdatedTimeText: String = "",
)

enum class DrawerFocus {
    LIST,
}

enum class DrawerListAlignment {
    LEFT,
    CENTER,
    RIGHT,
}

enum class LauncherMode {
    HOME,
    APP_DRAWER,
    SETTINGS,
    SMS_ROLE_PROMPT,
    SMS_THREADS,
    SMS_THREAD_DETAIL,
    SMS_INBOX,
    APP_MANAGEMENT,
    DATA_HEALTH,
    NOTIFICATION_SETTINGS,
    DIAGNOSTICS,
    IDLE,
}

enum class SmsPermissionState {
    MISSING,
    READ_ONLY,
    READY,
}
