package com.purride.pixellauncherv2.render

data class IdleFluidTuning(
    val disturbanceDurationMs: Long,
    val defaultGravityY: Float,
    val earthGravity: Float,
    val particleRadius: Float,
    val particleDensity: Float,
    val coverageRadiusPx: Float,
    val onThreshold: Float,
    val offThreshold: Float,
    val trendDeltaThreshold: Float,
    val minGravityMagnitude: Float,
    val minHalfExtent: Float,
    val minFluidThickness: Float,
    val freeSurfaceBandThickness: Float,
    val surfaceSpawnOffset: Float,
    val surfaceSpawnJitter: Float,
    val surfaceLateralJitter: Float,
    val minDisturbanceAccel: Float,
    val maxUsefulLinearAccel: Float,
    val maxDisturbanceAcceleration: Float,
    val gravityScaleReferenceHeight: Float,
    val minGravityScale: Float,
    val maxGravityScale: Float,
    val baseParticleDamping: Float,
    val minParticleDamping: Float,
    val maxParticleDamping: Float,
    val gravityContribution: Float,
    val disturbanceContribution: Float,
    val worldVelocityIterations: Int,
    val worldPositionIterations: Int,
    val minStepSeconds: Float,
    val maxStepSeconds: Float,
    val minSimulationSize: Int,
) {
    companion object {
        const val defaultDisturbanceDurationMs: Long = 320L

        fun default(): IdleFluidTuning {
            return IdleFluidTuning(
                disturbanceDurationMs = defaultDisturbanceDurationMs,
                defaultGravityY = 9.81f,
                earthGravity = 9.81f,
                particleRadius = 0.50f,
                particleDensity = 1f,
                coverageRadiusPx = 1.35f,
                onThreshold = 0.20f,
                offThreshold = 0.16f,
                trendDeltaThreshold = 0.012f,
                minGravityMagnitude = 0.2f,
                minHalfExtent = 0.25f,
                minFluidThickness = 0.75f,
                freeSurfaceBandThickness = 1.8f,
                surfaceSpawnOffset = 0.50f,
                surfaceSpawnJitter = 0.12f,
                surfaceLateralJitter = 0.28f,
                minDisturbanceAccel = 0.55f,
                maxUsefulLinearAccel = 6.5f,
                maxDisturbanceAcceleration = 1.8f,
                gravityScaleReferenceHeight = 64f,
                minGravityScale = 0.90f,
                maxGravityScale = 1.40f,
                baseParticleDamping = 0.11f,
                minParticleDamping = 0.08f,
                maxParticleDamping = 0.17f,
                gravityContribution = 0.01f,
                disturbanceContribution = 0.028f,
                worldVelocityIterations = 6,
                worldPositionIterations = 3,
                minStepSeconds = 0.010f,
                maxStepSeconds = 0.033f,
                minSimulationSize = 4,
            )
        }
    }
}
