// 由 tools/generate_pixel_font_catalog.py 生成；禁止手工修改。
package com.purride.pixeldesign.font

/** 由 fonts/font_catalog.json 生成的只读字体目录。 */
internal object GeneratedProductFontCatalog {
    /** 按设置页展示顺序排列的全部字体家族。 */
    val families: List<ProductFontFamilyDescriptor> = listOf(
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("fusion"),
            constantName = "FUSION",
            displayLabel = "FUSION",
            assetFamilyId = "fusion_pixel",
            sourceVersion = "2026.02.27",
            licenseId = "OFL-1.1",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("fusion"),
                widthMode = ProductFontWidthMode.PROPORTIONAL,
                size = ProductFontSize(10),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("fusion"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(8),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(8),
                        cellHeight = 12,
                        baseline = 9,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 8,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_8px_proportional_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_proportional_latin",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-8px-proportional-latin.bdf.gz",
                            sourceSha256 = "219c0a9f0e7263c9d4fcb833ea2c5bb1324a58a3ac7e929cf2fcbe46010e8f8c",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 4,
                        ),
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_8px_proportional_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_proportional_zh_hans",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-8px-proportional-zh_hans.bdf.gz",
                            sourceSha256 = "ac6946a9d4c6f8a3439c83bbb3eee19ffc812faa1b51d0a09598cf9877e98168",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 8,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("fusion"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(10),
                        cellHeight = 14,
                        baseline = 11,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_10px_proportional_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_proportional_latin",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-10px-proportional-latin.bdf.gz",
                            sourceSha256 = "e15f45b1699a9e2f377d8f6465740eefe7b0736eb586b39d72197575c92b9792",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 6,
                        ),
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_10px_proportional_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_proportional_zh_hans",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-10px-proportional-zh_hans.bdf.gz",
                            sourceSha256 = "1e8e8ed62ab1ce4d883f4bc92ddbf14125efb0cb41367b5da68752a738ae8ed1",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 10,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("fusion"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(12),
                        cellHeight = 16,
                        baseline = 13,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_12px_proportional_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_proportional_latin",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-12px-proportional-latin.bdf.gz",
                            sourceSha256 = "5688837abac20cd8b7361bfcd6b29f4b0ae5d2d7d744fce408e8aa0f36c9fa65",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 8,
                        ),
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_12px_proportional_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_proportional_zh_hans",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-12px-proportional-zh_hans.bdf.gz",
                            sourceSha256 = "1fd5c9c357e8d0512a37ddbff03156c437f0dd3a162c47014936f601fa64e886",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 12,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("fusion"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(8),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(8),
                        cellHeight = 8,
                        baseline = 7,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 8,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_8px_monospaced_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_monospaced_latin",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-8px-monospaced-latin.bdf.gz",
                            sourceSha256 = "8b83e6e2566ead241f31af3cccc8b087b886fad2c1c9fac8fa85d601543dfd30",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 8,
                        ),
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_8px_monospaced_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_8px_monospaced_zh_hans",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-8px-monospaced-zh_hans.bdf.gz",
                            sourceSha256 = "9974d0a1853635a86627687b3c874e129da708af8c13b627c3064a427e9b1657",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 8,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("fusion"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(10),
                        cellHeight = 10,
                        baseline = 9,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_10px_monospaced_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_monospaced_latin",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-10px-monospaced-latin.bdf.gz",
                            sourceSha256 = "7bcd9c9b50765584a25365d96daa36fe1c65a440aa1ff531149ec2ac91b209b4",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 10,
                        ),
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_10px_monospaced_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_10px_monospaced_zh_hans",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-10px-monospaced-zh_hans.bdf.gz",
                            sourceSha256 = "f1b60ba223a28e8e7792613d8f51494b0e55fe16f4936b75e7e951bc1f257fe9",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 10,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("fusion"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(12),
                        cellHeight = 12,
                        baseline = 10,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_12px_monospaced_latin",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_monospaced_latin",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-12px-monospaced-latin.bdf.gz",
                            sourceSha256 = "0d494b6dfb6d572ac4887548c1098e734b3f7a82961531b5a907559c74bbdca7",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 12,
                        ),
                        ProductFontPackDescriptor(
                            id = "fusion_pixel_12px_monospaced_zh_hans",
                            assetDirectory = "glyphpacks/fusion_pixel_12px_monospaced_zh_hans",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/fusion_pixel/2026.02.27/fusion-pixel-12px-monospaced-zh_hans.bdf.gz",
                            sourceSha256 = "2da19341cb7d3aa550e37af3fba1c0e580f22d7e9c2f9e5c534e70eb3145f434",
                            rangeSet = "standard",
                            coverageRanges = listOf("0020-007E", "00A0-00FF", "0100-024F", "0370-03FF", "0400-04FF", "2000-206F", "2070-209F", "2100-214F", "2460-24FF", "3000-303F", "3040-309F", "30A0-30FF", "3100-312F", "3130-318F", "3200-32FF", "3300-33FF", "3400-4DBF", "4E00-9FFF", "FF00-FFEF"),
                            defaultAdvance = 12,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("ark"),
            constantName = "ARK",
            displayLabel = "ARK",
            assetFamilyId = "ark_pixel",
            sourceVersion = "2026.07.20",
            licenseId = "OFL-1.1",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("ark"),
                widthMode = ProductFontWidthMode.PROPORTIONAL,
                size = ProductFontSize(10),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("ark"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(10),
                        cellHeight = 14,
                        baseline = 11,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "ark_pixel_10px_proportional_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_10px_proportional_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-10px-proportional-zh_cn.bdf",
                            sourceSha256 = "4cdb03df957b45439658944ea8eda169113cb4276e8ac52ec236dab794501c31",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 5,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("ark"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(12),
                        cellHeight = 16,
                        baseline = 13,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "ark_pixel_12px_proportional_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_12px_proportional_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-12px-proportional-zh_cn.bdf",
                            sourceSha256 = "e83acfb188b82c5ae0384b59afaf92d38795c30235afa69e2f8d6ad08f13ce6c",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 6,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("ark"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(16),
                        cellHeight = 22,
                        baseline = 17,
                        narrowAdvanceWidth = 7,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "ark_pixel_16px_proportional_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_16px_proportional_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-16px-proportional-zh_cn.bdf",
                            sourceSha256 = "694fa5400941e6281b025e59e3cdddea0a306fca246e8e12e0d004fbcab8c109",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 7,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("ark"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(10),
                        cellHeight = 10,
                        baseline = 9,
                        narrowAdvanceWidth = 5,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "ark_pixel_10px_monospaced_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_10px_monospaced_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-10px-monospaced-zh_cn.bdf",
                            sourceSha256 = "7e2d5351b5121e2c1343cada1a076cd4f7724aef2f4617a1c3a8b10c5af8d236",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 5,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("ark"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(12),
                        cellHeight = 12,
                        baseline = 10,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "ark_pixel_12px_monospaced_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_12px_monospaced_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-12px-monospaced-zh_cn.bdf",
                            sourceSha256 = "bf1ba88061952a88ae15b8fb67f55a69589f73bd77296fe31eafaaed36d38e39",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 6,
                        ),
                    ),
                ),
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("ark"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(16),
                        cellHeight = 16,
                        baseline = 13,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "ark_pixel_16px_monospaced_zh_cn",
                            assetDirectory = "glyphpacks/ark_pixel_16px_monospaced_zh_cn",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/ark_pixel/2026.07.20/ark-pixel-16px-monospaced-zh_cn.bdf",
                            sourceSha256 = "24784e5587ecd288e2770aab0656b1b355e8e5ade572e3937662d20524227aec",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 8,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("cubic_11"),
            constantName = "CUBIC_11",
            displayLabel = "CUBIC 11",
            assetFamilyId = "cubic_11",
            sourceVersion = "1.500",
            licenseId = "OFL-1.1",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("cubic_11"),
                widthMode = ProductFontWidthMode.PROPORTIONAL,
                size = ProductFontSize(12),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("cubic_11"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(12),
                        cellHeight = 14,
                        baseline = 10,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 13,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "cubic_11_12px_proportional",
                            assetDirectory = "glyphpacks/cubic_11_12px_proportional",
                            sourceType = "outline",
                            sourcePath = "tools/font_sources/cubic_11/1.500/Cubic_11.ttf",
                            sourceSha256 = "0193f5f033612496df6b45ee92ac3b335bc6a5a24ff95da55ca87b33e57dcf62",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 4,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("boutique_7"),
            constantName = "BOUTIQUE_7",
            displayLabel = "BOUTIQUE 7",
            assetFamilyId = "boutique_7",
            sourceVersion = "2026.03.30",
            licenseId = "OFL-1.1",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("boutique_7"),
                widthMode = ProductFontWidthMode.PROPORTIONAL,
                size = ProductFontSize(8),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("boutique_7"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(8),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(8),
                        cellHeight = 8,
                        baseline = 6,
                        narrowAdvanceWidth = 3,
                        wideAdvanceWidth = 8,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "boutique_7_8px_proportional",
                            assetDirectory = "glyphpacks/boutique_7_8px_proportional",
                            sourceType = "outline",
                            sourcePath = "tools/font_sources/boutique_bitmap_7/current-2026.03.30/BoutiqueBitmap7x7.ttf",
                            sourceSha256 = "25b76e6e0545ca46f3be26b8fc179e0a6af40367ded75aeada3b56a61fa3cda1",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 3,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("boutique_9"),
            constantName = "BOUTIQUE_9",
            displayLabel = "BOUTIQUE 9",
            assetFamilyId = "boutique_9",
            sourceVersion = "1.93",
            licenseId = "OFL-1.1",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("boutique_9"),
                widthMode = ProductFontWidthMode.PROPORTIONAL,
                size = ProductFontSize(10),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("boutique_9"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(10),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(10),
                        cellHeight = 11,
                        baseline = 8,
                        narrowAdvanceWidth = 4,
                        wideAdvanceWidth = 10,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "boutique_9_10px_proportional",
                            assetDirectory = "glyphpacks/boutique_9_10px_proportional",
                            sourceType = "outline",
                            sourcePath = "tools/font_sources/boutique_bitmap_9/1.93/BoutiqueBitmap9x9_1.93.ttf",
                            sourceSha256 = "7210391e4252471fbd9b62f65d86f1f7bcdc7f8beb4fc1feeb3ad8b65a0e85e8",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 4,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("dotted"),
            constantName = "DOTTED",
            displayLabel = "DOTTED",
            assetFamilyId = "dotted",
            sourceVersion = "0.1",
            licenseId = "GPL-2.0",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("dotted"),
                widthMode = ProductFontWidthMode.PROPORTIONAL,
                size = ProductFontSize(13),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("dotted"),
                        widthMode = ProductFontWidthMode.PROPORTIONAL,
                        size = ProductFontSize(13),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(13),
                        cellHeight = 14,
                        baseline = 10,
                        narrowAdvanceWidth = 9,
                        wideAdvanceWidth = 13,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "dotted_13px_proportional",
                            assetDirectory = "glyphpacks/dotted_13px_proportional",
                            sourceType = "dot_grid_otf",
                            sourcePath = "tools/font_sources/dotted_songti/0.1/DottedSongtiSquareRegular.otf",
                            sourceSha256 = "c5823b88b35937b638b85cf8ba35d4b9a94b4d3b58c981550ddca7cb39c86714",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 9,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("gnu_unifont"),
            constantName = "GNU_UNIFONT",
            displayLabel = "UNIFONT",
            assetFamilyId = "gnu_unifont",
            sourceVersion = "17.0.04",
            licenseId = "GPL-2.0+",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("gnu_unifont"),
                widthMode = ProductFontWidthMode.MONOSPACED,
                size = ProductFontSize(16),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("gnu_unifont"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(16),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(16),
                        cellHeight = 16,
                        baseline = 14,
                        narrowAdvanceWidth = 8,
                        wideAdvanceWidth = 16,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "gnu_unifont_16px_monospaced",
                            assetDirectory = "glyphpacks/gnu_unifont_16px_monospaced",
                            sourceType = "bdf",
                            sourcePath = "tools/font_sources/gnu_unifont/17.0.04/unifont-17.0.04.bdf.gz",
                            sourceSha256 = "9a2de4826388242771121c7fe00e412523c318318b8ee38e6be6cd454e7ec802",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 8,
                        ),
                    ),
                ),
            ),
        ),
        ProductFontFamilyDescriptor(
            id = ProductFontFamily("pix32"),
            constantName = "PIX32",
            displayLabel = "PIX32",
            assetFamilyId = "pix32",
            sourceVersion = "1.9.7",
            licenseId = "commercial-purchased-user-declared",
            defaultKey = ProductFontFaceKey(
                family = ProductFontFamily("pix32"),
                widthMode = ProductFontWidthMode.MONOSPACED,
                size = ProductFontSize(12),
            ),
            faces = listOf(
                ProductFontFaceDescriptor(
                    key = ProductFontFaceKey(
                        family = ProductFontFamily("pix32"),
                        widthMode = ProductFontWidthMode.MONOSPACED,
                        size = ProductFontSize(12),
                    ),
                    settingsVisible = true,
                    roles = setOf(ProductTextRole.CHROME),
                    metrics = ProductFontMetrics(
                        size = ProductFontSize(12),
                        cellHeight = 12,
                        baseline = 11,
                        narrowAdvanceWidth = 6,
                        wideAdvanceWidth = 12,
                    ),
                    packs = listOf(
                        ProductFontPackDescriptor(
                            id = "pix32_12px_monospaced",
                            assetDirectory = "glyphpacks/pix32_12px_monospaced",
                            sourceType = "outline",
                            sourcePath = "tools/font_sources/pix32/1.9.7/Pixel32.v1.9.7.ttf",
                            sourceSha256 = "06a8a1714f77ca598177e2ac1d3b4af14f4c04c1acf101f1fcbc2af2a136c451",
                            rangeSet = "bmp",
                            coverageRanges = listOf("0020-D7FF", "E000-FFFD"),
                            defaultAdvance = 6,
                        ),
                    ),
                ),
            ),
        ),
    )
}
